=== kjellski/VM-Automation-Framework/src/JobManagerInterfaces/schema/Package.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.rbadams.com/Automation/Package"
    elementFormDefault="qualified" 
    xmlns:tns="http://www.rbadams.com/Automation/Package">
    
    <xs:complexType name="PathT">
        <xs:attribute name="Path" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                <xs:minLength value="1" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="PathType" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="BuildRelative"/>
                    <xs:enumeration value="Absolute"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="Name" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
        <xs:complexType name="Package">
            <xs:all>
                <xs:element name="MainDirectory" type="tns:PathT"/>
                <xs:element name="AdditionalSubDirectories" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SubDirectory" type="tns:PathT" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DLLFileName">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="JobRunnerClassName">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="RequiredJobProperties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PropertyName" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Key" type="xs:string" use="required"/>
                                    <xs:attribute name="Value" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="RequiredISOs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ISOName" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    <xs:element name="Package" type="tns:Package" />
</xs:schema>

=== kjellski/VM-Automation-Framework/samples/Configuration/Packages/RunNominalTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://www.rbadams.com/Automation/Package"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rbadams.com/Automation/Package ../../../src/JobManagerInterfaces/schema/Package.xsd">
    <MainDirectory Path="Tests\Automation\ETP\RunBVTTests\bin\Release" PathType="BuildRelative"/>
    <AdditionalSubDirectories>
      <SubDirectory Name="SomeTestPackage" Path="Tests\SomeTestPackage\bin\Release" PathType="BuildRelative"/>
	  <SubDirectory Name="SomeOtherTestPackage" Path="Tests\SomeOtherTestPackage\bin\Release" PathType="BuildRelative"/>
    </AdditionalSubDirectories>
    <DLLFileName>RunBVTTests.dll</DLLFileName>
    <JobRunnerClassName>RunBVTTests.Main</JobRunnerClassName>
    <RequiredJobProperties/>
    <Properties>
      <!-- Allow Tests up to 60 minutes to run -->
      <Property Key="testTimeoutMin" Value="60"/>
      <Property Key="Tests" Value="SomeTestPackage\SomeTest.dll;SomeOtherTestPackage\SomeOtherTest.dll"/>
      <Property Key="Package_NUnitCategories" Value="nominal"/>
      <Property Key="TreatFailedTestsAsPackageFailure" Value="true"/>
    </Properties>
    <RequiredISOs />
</Package>

=== kjellski/VM-Automation-Framework/samples/Configuration/Packages/UninstallApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://www.rbadams.com/Automation/Package"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rbadams.com/Automation/Package ../../../src/JobManagerInterfaces/schema/Package.xsd">
  <MainDirectory Path="Tests\Automation\ETP\InstallFlagstaff\bin\Release" PathType="BuildRelative"/>
  <AdditionalSubDirectories/>
  <DLLFileName>InstallApp.dll</DLLFileName>
  <JobRunnerClassName>InstallApp.Main</JobRunnerClassName>
  <RequiredJobProperties />
  <Properties>
    <Property Key="UninstallApp" Value="true"/>
  </Properties>
  <RequiredISOs/>
</Package>

=== kjellski/VM-Automation-Framework/samples/Configuration/Packages/RunPostRestartTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://www.rbadams.com/Automation/Package"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rbadams.com/Automation/Package ../../../src/JobManagerInterfaces/schema/Package.xsd">
    <MainDirectory Path="Tests\Automation\ETP\RunBVTTests\bin\Release" PathType="BuildRelative"/>
    <AdditionalSubDirectories>
      <SubDirectory Name="InstallerTest" Path="Tests\Installation\InstallerTest\bin\Release" PathType="BuildRelative"/>
    </AdditionalSubDirectories>
    <DLLFileName>RunBVTTests.dll</DLLFileName>
    <JobRunnerClassName>RunBVTTests.Main</JobRunnerClassName>
    <RequiredJobProperties/>
    <Properties>
      <Property Key="Tests" Value="InstallerTest\InstallerTest.dll"/>
      <Property Key="Package_NUnitCategories" Value="PostRestart"/>
      <Property Key="ExcludeConfigurationCategories" Value="true"/>
      <Property Key="ExcludeJobCategories" Value="true"/>
    </Properties>
    <RequiredISOs />
</Package>

=== kjellski/VM-Automation-Framework/samples/Configuration/Packages/WindowsUpdate.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://www.rbadams.com/Automation/Package"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rbadams.com/Automation/Package ../../../src/JobManagerInterfaces/schema/Package.xsd">
    <MainDirectory Path="Tests\Automation\ETP\WindowsUpdatesInstallJob\bin\Release" PathType="BuildRelative"/>
    <AdditionalSubDirectories/>
    <DLLFileName>WindowsUpdatesInstallJob.dll</DLLFileName>
    <JobRunnerClassName>WindowsUpdatesInstallJob.Main</JobRunnerClassName>
    <RequiredJobProperties />
    <Properties/>
    <RequiredISOs />
</Package>

=== kjellski/VM-Automation-Framework/samples/Configuration/Packages/InstallApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://www.rbadams.com/Automation/Package"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rbadams.com/Automation/Package ../../../src/JobManagerInterfaces/schema/Package.xsd">
    <MainDirectory Path="Tests\Automation\ETP\InstallApp\bin\Release" PathType="BuildRelative"/>
    <AdditionalSubDirectories/>
    <DLLFileName>InstallApp.dll</DLLFileName>
    <JobRunnerClassName>InstallApp.Main</JobRunnerClassName>
    <RequiredJobProperties />
    <Properties/>
    <RequiredISOs>
        <ISOName>Main</ISOName>
    </RequiredISOs>
</Package>
